# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# primary rules
rules:
# dropdown: area
- valueFor: 'Area'
  contains: 'Other'
  addLabels: ['other']
- valueFor: 'Area'
  contains: 'Applications'
  addLabels: ['applications']
- valueFor: 'Area'
  contains: 'Api'
  addLabels: ['api']
- valueFor: 'Area'
  contains: 'Board support'
  addLabels: ['board support']
- valueFor: 'Area'
  contains: 'Build System'
  addLabels: ['build system']
- valueFor: 'Area'
  contains: 'Configuring'
  addLabels: ['configuring']
- valueFor: 'Area'
  contains: 'Debugging'
  addLabels: ['debugging']
- valueFor: 'Area'
  contains: 'Drivers'
  addLabels: ['drivers']
- valueFor: 'Area'
  contains: 'File System'
  addLabels: ['file system']
- valueFor: 'Area'
  contains: 'Installing'
  addLabels: ['installing']
- valueFor: 'Area'
  contains: 'Kconfig'
  addLabels: ['kconfig']
- valueFor: 'Area'
  contains: 'Kernel'
  addLabels: ['kernel']
- valueFor: 'Area'
  contains: 'Memory Management'
  addLabels: ['memory management']
- valueFor: 'Area'
  contains: 'Native port'
  addLabels: ['native port']
- valueFor: 'Area'
  contains: 'Networking'
  addLabels: ['networking']
- valueFor: 'Area'
  contains: 'OS Components'
  addLabels: ['os components']
- valueFor: 'Area'
  contains: 'Posix'
  addLabels: ['posix']
- valueFor: 'Area'
  contains: 'Sensors'
  addLabels: ['sensors']
- valueFor: 'Area'
  contains: 'Specific Peripheral'
  addLabels: ['specific peripheral']
# dropdown: architecture
- valueFor: 'Architecture'
  contains: 'all'
  addLabels: ['all']
- valueFor: 'Architecture'
  contains: 'arm'
  addLabels: ['arm']
- valueFor: 'Architecture'
  contains: 'arm64'
  addLabels: ['arm64']
- valueFor: 'Architecture'
  contains: 'avr'
  addLabels: ['avr']
- valueFor: 'Architecture'
  contains: 'ceva'
  addLabels: ['ceva']
- valueFor: 'Architecture'
  contains: 'hc'
  addLabels: ['hc']
- valueFor: 'Architecture'
  contains: 'mips'
  addLabels: ['mips']
- valueFor: 'Architecture'
  contains: 'misoc'
  addLabels: ['misoc']
- valueFor: 'Architecture'
  contains: 'openrisc'
  addLabels: ['openrisc']
- valueFor: 'Architecture'
  contains: 'renesas'
  addLabels: ['renesas']
- valueFor: 'Architecture'
  contains: 'risc-v'
  addLabels: ['risc-v']
- valueFor: 'Architecture'
  contains: 'simulator'
  addLabels: ['simulator']
- valueFor: 'Architecture'
  contains: 'sparc'
  addLabels: ['sparc']
- valueFor: 'Architecture'
  contains: 'tricore'
  addLabels: ['tricore']
- valueFor: 'Architecture'
  contains: 'x86'
  addLabels: ['x86']
- valueFor: 'Architecture'
  contains: 'x86_64'
  addLabels: ['x86_64']
- valueFor: 'Architecture'
  contains: 'xtensa'
  addLabels: ['xtensa']
- valueFor: 'Architecture'
  contains: 'z16'
  addLabels: ['z16']
- valueFor: 'Architecture'
  contains: 'z80'
  addLabels: ['z80']
