name: Bug report
description: Report a bug to improve NuttX stability
title: "[BUG] import/path: bug <title>"
labels: [👀 needs triage, bug]
body:
  - type: markdown
    attributes:
      value: |
        Hello NuttX Community member! Please keep things tidy by putting your post in the proper place:

        Reporting a bug: use this form.
        Asking a question or getting help: use the [General Help](https://github.com/simbit18/nuttx-testing-templates/issues/new?assignees=&labels=question&projects=&template=003_help.yml&title=help%3A+help+title) form or [Mailing list](https://nuttx.apache.org/community/).
        Requesting a new feature: use the [Feature request](https://github.com/simbit18/nuttx-testing-templates/issues/new?assignees=&labels=enhancement&projects=&template=002_feature_request.yml) form.
  - type: textarea
    attributes:
      label: "Description / Steps to reproduce the issue"
      description: "A clear and concise description of what the bug is, and why you consider it to be a bug, and steps for how to reproduce it"
      placeholder: |
        A description with steps to reproduce the issue.
        May include logs, images, or videos.
        1. Step 1
        2. Step 2
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Environment

        Please specify your environment.
  - type: input
    attributes:
      label: "Operating system/version"
      description: On which OS does this issue occur?
      placeholder: "eg. Ubuntu 20.4, macOS 13, Windows/MSYS_NT-10.0-19045, ecc"
    validations:
      required: true

  - type: input
    attributes:
      label: "NuttX Version"
      placeholder: "eg. master, 12.5.1, ecc"
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Issue Architecture
      description: What architecture(s) are you seeing the problem on?
      multiple: true
      options:
        - "Architecture: all"
        - "Architecture: arm"
        - "Architecture: arm64"
        - "avr"
        - "Architecture: ceva"
        - "Architecture: hc"
        - "Architecture: mips"
        - "Architecture: misoc"
        - "Architecture: ort1k"
        - "Architecture: renesas"
        - "Architecture: risc-v"
        - "Architecture: sim"
        - "Architecture: sparc"
        - "Architecture: tricore"
        - "Architecture: x86"
        - "Architecture: x86_64"
        - "Architecture: xtensa"
        - "Architecture: z16"
        - "Architecture: z80"
    validations:
      required: true

  - type: input
    id: area
    attributes:
      label: Related area
      description: Please briefly explain the area of your Feature Request.
      placeholder: "eg. area: Board support, specific Peripheral, GPIO, Wifi..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Before You Submit

        Please verify that you've followed these steps:
          - Confirm the problem is reproducible on [**master**](https://github.com/apache/nuttx) or [**latest stable**](https://nuttx.apache.org/download) release.
          - Run `make distclean` when encountering build issues.
          - Search [existing issues](https://github.com/apache/nuttx/issues) (including [closed](https://github.com/apache/nuttx/issues?q=is%3Aissue+is%3Aclosed))
          - Read the [FAQ](https://nuttx.apache.org/docs/latest/faq/index.html).

  - type: checkboxes
    attributes:
      label: "Verification"
      options:
        - label: "I have verified before submitting the report."
          required: true