name: Labeler
on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/checkout@v4
    - uses: damccorm/tag-ur-it@6fa72bbf1a2ea157b533d7e7abeafdb5855dbea5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: "./.github/issue-rules.yml"
